#   ▄▀▀▄▀▀▀▄  ▄▀▀▀▀▄      ▄▀▀▄▀▀▀▄
#  █   █   █ █    █      █   █   █
#  ▐  █▀▀█▀  ▐    █      ▐  █▀▀█▀
#   ▄▀    █      █        ▄▀    █
#  █     █     ▄▀▄▄▄▄▄▄▀ █     █
#  ▐     ▐     █         ▐     ▐
#              ▐
#
# This is the main configuration file for RamLimitRestart
# This file contains all the configuration options for RamLimitRestart
#
# If you need help with the configuration or have any questions related to RamLimitRestart,
# join my Discord server: https://discord.angelillo15.es/ or watch its docs https://docs.angelillo15.es/rlr
#
# RamLimitRestart by Angelillo15 | https://angelillo15.es
# RamLimitRestart is licensed under the GNU General Public License v3.0
#
Config:
  # The ram free limit in MB
  # When the ram free limit is reached, the server will restart
  limit: 1024 # 1GB -> 1024MB you can calculate doing XGB * 1024 = the limit in MB
  # The command/s to run when the ram limit is reached
  commands:
    - "bc Ram limit reached, restarting the server..."
    - "restart"
  check-interval: 5 # in seconds
  debug: false # Enable debug mode

  # Pterodactyl configuration section
  pterodactyl:
    # You can find the server UUID in the URL of the server in the panel
    # for example: https://panel.example.com/server/<server-id>
    # The server UUID is the <server-id> part
    serverUUID: "your-server-uuid"
    # Your panel url
    panel-url: "https://panel.example.com/"
    # Your panel API key
    # You can find it in your panel profile https://panel.example.com/account/api
    api-key: "your-api-key"
Messages:
  # This message will be sent to the console when the debug mode is enabled
  debug-message: "&7[&bRamLimitRestart&7] Memory in usage: %memory_usage%, Memory free: %memory_free%, Memory limit: %memory_max%"



